Fix the test failures when in bom weekly
When the PCT was being run again bom weekly, test was failing with error like,

```
[ERROR] hudson.slaves.CommandLauncherForceSandboxTest.editCommandLauncherUI_ForceSandboxTrue -- Time elapsed: 120.6 s <<< ERROR!
org.htmlunit.FailingHttpStatusCodeException: 404 Not Found for http://localhost:56615/jenkins/login
```

When opening the `/jenkins` endpoint in the browser by pausing the test, it was rendering a File server view instead of Jenkins application.

Possibly linked to https://github.com/jenkinsci/jenkins-test-harness/pull/906 and  https://github.com/jenkinsci/jenkins/pull/10227